# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64dd80d284a91aa04e1c18efc53e6f74b19007c9744a7dbd444832e846cd7addb1da587eb98afe77d728ad712582d57ee43a1a30f6e64ea0fb21ba35d79a558b

test:
  secret_key_base: 60c90eabb5470bb4d97941c85e898f9ab1412a6023648a5853dbc6c43affe5e32ff5bc10e41d9e8e378d08f7999be524de2cd31e69e85dbe6127b6e1b7e9bde0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
